/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTable;

/**
 *
 * @author User
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        lblPozdrav = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        miKreirajP = new javax.swing.JMenuItem();
        miPretraziP = new javax.swing.JMenuItem();
        MenuZ = new javax.swing.JMenu();
        miKreirajZ = new javax.swing.JMenuItem();
        miPretraziZ = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        miKreirajT = new javax.swing.JMenuItem();
        miPretraziT = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miKreirajM = new javax.swing.JMenuItem();
        miPretraziM = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miKreirajD = new javax.swing.JMenuItem();
        miPretraziD = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        miKreirajI = new javax.swing.JMenuItem();
        miPrikaziI = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu5.setText("jMenu5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPozdrav.setText("jLabel1");

        jMenu3.setText("Poslovni partner");

        miKreirajP.setText("Kreiraj");
        jMenu3.add(miKreirajP);

        miPretraziP.setText("Prikaži");
        miPretraziP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziPActionPerformed(evt);
            }
        });
        jMenu3.add(miPretraziP);

        jMenuBar2.add(jMenu3);

        MenuZ.setText("Zaposleni");

        miKreirajZ.setText("Kreiraj");
        miKreirajZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKreirajZActionPerformed(evt);
            }
        });
        MenuZ.add(miKreirajZ);

        miPretraziZ.setText("Prikaži");
        miPretraziZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziZActionPerformed(evt);
            }
        });
        MenuZ.add(miPretraziZ);

        jMenuBar2.add(MenuZ);

        jMenu6.setText("Trotinet");

        miKreirajT.setText("Kreiraj");
        jMenu6.add(miKreirajT);

        miPretraziT.setText("Prikaži");
        miPretraziT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziTActionPerformed(evt);
            }
        });
        jMenu6.add(miPretraziT);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Mesto");

        miKreirajM.setText("Kreiraj");
        jMenu7.add(miKreirajM);

        miPretraziM.setText("Prikaži");
        miPretraziM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziMActionPerformed(evt);
            }
        });
        jMenu7.add(miPretraziM);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Termin dežurstva");

        miKreirajD.setText("Kreiraj");
        jMenu8.add(miKreirajD);

        miPretraziD.setText("Prikaži");
        miPretraziD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretraziDActionPerformed(evt);
            }
        });
        jMenu8.add(miPretraziD);

        jMenuBar2.add(jMenu8);

        jMenu4.setText("Iznajmljivajne");

        miKreirajI.setText("Kreiraj");
        jMenu4.add(miKreirajI);

        miPrikaziI.setText("Prikaži");
        jMenu4.add(miPrikaziI);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblPozdrav)
                .addContainerGap(903, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPozdrav)
                .addContainerGap(463, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPretraziPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziPActionPerformed

    private void miPretraziZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziZActionPerformed

    private void miPretraziTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziTActionPerformed

    private void miPretraziMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziMActionPerformed

    private void miPretraziDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretraziDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miPretraziDActionPerformed

    private void miKreirajZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKreirajZActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miKreirajZActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuZ;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblPozdrav;
    private javax.swing.JMenuItem miKreirajD;
    private javax.swing.JMenuItem miKreirajI;
    private javax.swing.JMenuItem miKreirajM;
    private javax.swing.JMenuItem miKreirajP;
    private javax.swing.JMenuItem miKreirajT;
    private javax.swing.JMenuItem miKreirajZ;
    private javax.swing.JMenuItem miPretraziD;
    private javax.swing.JMenuItem miPretraziM;
    private javax.swing.JMenuItem miPretraziP;
    private javax.swing.JMenuItem miPretraziT;
    private javax.swing.JMenuItem miPretraziZ;
    private javax.swing.JMenuItem miPrikaziI;
    // End of variables declaration//GEN-END:variables



    public JLabel getLblPozdrav() {
        return lblPozdrav;
    }

    public void setLblPozdrav(JLabel lblPozdrav) {
        this.lblPozdrav = lblPozdrav;
    }

    public JMenuItem getMiKreirajD() {
        return miKreirajD;
    }

    public void setMiKreirajD(JMenuItem miKreirajD) {
        this.miKreirajD = miKreirajD;
    }

    public JMenuItem getMiKreirajM() {
        return miKreirajM;
    }

    public void setMiKreirajM(JMenuItem miKreirajM) {
        this.miKreirajM = miKreirajM;
    }

    public JMenuItem getMiKreirajP() {
        return miKreirajP;
    }

    public void setMiKreirajP(JMenuItem miKreirajP) {
        this.miKreirajP = miKreirajP;
    }

    public JMenuItem getMiKreirajT() {
        return miKreirajT;
    }

    public void setMiKreirajT(JMenuItem miKreirajT) {
        this.miKreirajT = miKreirajT;
    }

    public JMenuItem getMiKreirajZ() {
        return miKreirajZ;
    }

    public void setMiKreirajZ(JMenuItem miKreirajZ) {
        this.miKreirajZ = miKreirajZ;
    }






 



    public void setMiPretraziD(JMenuItem miPretraziD) {
        this.miPretraziD = miPretraziD;
    }

    public JMenuItem getMiPretraziM() {
        return miPretraziM;
    }

    public void setMiPretraziM(JMenuItem miPretraziM) {
        this.miPretraziM = miPretraziM;
    }

    public JMenuItem getMiPretraziP() {
        return miPretraziP;
    }

    public void setMiPretraziP(JMenuItem miPretraziP) {
        this.miPretraziP = miPretraziP;
    }

    public JMenuItem getMiPretraziT() {
        return miPretraziT;
    }

    public void setMiPretraziT(JMenuItem miPretraziT) {
        this.miPretraziT = miPretraziT;
    }

    public JMenuItem getMiPretraziZ() {
        return miPretraziZ;
    }

    public void setMiPretraziZ(JMenuItem miPretraziZ) {
        this.miPretraziZ = miPretraziZ;
    }








    public void kreirajMestoAddActionListener(ActionListener actionListener) {
         miKreirajM.addActionListener(actionListener);
    }
    

      
      public void pretraziMestoAddActionListener(ActionListener actionListener) {
         miPretraziM.addActionListener(actionListener);
    }
      
      public void kreirajTrotinetAddActionListener(ActionListener actionListener) {
         miKreirajT.addActionListener(actionListener);
    }
      


    public void pretraziTrotinetAddActionListener(ActionListener actionListener) {
        miPretraziT.addActionListener(actionListener);
    }
    
    public void kreirajZaposleniAddActionListener(ActionListener actionListener) {
         miKreirajZ.addActionListener(actionListener);
    }
      


    public void pretraziZaposleniAddActionListener(ActionListener actionListener) {
        miPretraziZ.addActionListener(actionListener);
    }
    
        public void kreirajTerminAddActionListener(ActionListener actionListener) {
         miKreirajD.addActionListener(actionListener);
    }
      
 

    public void pretraziTerminAddActionListener(ActionListener actionListener) {
        miPretraziD.addActionListener(actionListener);
    }
    
    public void kreirajPoslovniPartnerAddActionListener(ActionListener actionListener) {
         miKreirajP.addActionListener(actionListener);
    }
      
 

    public void pretraziPoslovniPartnerAddActionListener(ActionListener actionListener) {
        miPretraziP.addActionListener(actionListener);
    }
    
    public void kreirajIznajmljivanjeAddActionListener(ActionListener actionListener) {
         miKreirajI.addActionListener(actionListener);
    }
      
 

    public void pretraziIznajmljivanjeAddActionListener(ActionListener actionListener) {
        miPrikaziI.addActionListener(actionListener);
    }

}
