/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.modeli_tabela.ModelTblIznajmljivanje;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import modeli.Iznajmljivanje;
import modeli.PoslovniPartner;
import modeli.Zaposleni;
import operacije.Operacije;

/**
 *
 * @author User
 */
public class IznajmljivanjeForma extends javax.swing.JFrame {
    private List<Iznajmljivanje> iznajmljivanja=new ArrayList<>();
        private Zaposleni zaposleni=null;
        private PoslovniPartner pp=null;
        private int cenaStavki=0;
        
    /**
     * Creates new form IznajmljivanjeForma
     */
    public IznajmljivanjeForma(int operacija) {
        
        initComponents();
        
         switch(operacija){
         case Operacije.KreirajIznajmljivanje:
              
                
                btnPretrazi.setVisible(false);
                btnSelect.setVisible(false);
                jLabel1.setVisible(false);
                txtId.setVisible(false);
                btnSelect.setVisible(false);
                btnStavke1.setVisible(false);
                btnIzmeni.setVisible(false);
                break;
            
            
                
            case Operacije.PretraziIznajmljivanje:
                btnKreiraj.setVisible(false);
               btnIzmeni.setEnabled(false);
                
                break;
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKreiraj = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();
        btnPretrazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIzadji = new javax.swing.JButton();
        btnIzaberiZ = new javax.swing.JButton();
        lblZaposleni = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIznajmljivanje = new javax.swing.JTable();
        btnIzaberiP = new javax.swing.JButton();
        lblPartner = new javax.swing.JLabel();
        btnStavke1 = new javax.swing.JButton();
        btnIzmeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKreiraj.setText("Kreiraj");

        btnSelect.setText("Selektuj iznajmljivanje");

        btnPretrazi.setText("Pretraži");

        jLabel1.setText("ID:");

        jLabel3.setText("Poslovni partner:");

        btnIzadji.setText("Izadji");

        btnIzaberiZ.setText("Izaberi zaposlenog");

        lblZaposleni.setText("Zaposleni nije izabran");

        jLabel4.setText("Zaposleni:");

        tblIznajmljivanje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblIznajmljivanje);

        btnIzaberiP.setText("Izaberite partnera");

        lblPartner.setText("Partner nije izabran");

        btnStavke1.setText("Prikazi/Izmeni stavke iznajmljivanja");

        btnIzmeni.setText("Izmeni");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblZaposleni, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(lblPartner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPretrazi)
                        .addGap(3, 3, 3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIzaberiZ)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnIzaberiP)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)))
                .addGap(142, 142, 142))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSelect)
                                    .addComponent(btnIzadji)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(btnStavke1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnKreiraj)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPartner)
                            .addComponent(jLabel3)
                            .addComponent(btnIzaberiP))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblZaposleni)
                            .addComponent(btnIzaberiZ))
                        .addGap(18, 18, 18)
                        .addComponent(btnKreiraj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnPretrazi)
                        .addGap(18, 18, 18)
                        .addComponent(btnIzmeni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSelect)
                        .addGap(27, 27, 27)
                        .addComponent(btnStavke1)
                        .addGap(137, 137, 137)
                        .addComponent(btnIzadji)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberiP;
    private javax.swing.JButton btnIzaberiZ;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnSelect;
    private javax.swing.JButton btnStavke1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPartner;
    private javax.swing.JLabel lblZaposleni;
    private javax.swing.JTable tblIznajmljivanje;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
    
    
    
    public JButton getBtnIzaberi() {
        return btnIzaberiZ;
    }

    public void setBtnIzaberi(JButton btnIzaberi) {
        this.btnIzaberiZ = btnIzaberi;
    }

    public JButton getBtnIzadji() {
        return btnIzadji;
    }

    public void setBtnIzadji(JButton btnIzadji) {
        this.btnIzadji = btnIzadji;
    }

   

    public JButton getBtnKreiraj() {
        return btnKreiraj;
    }

    public int getCenaStavki() {
        return cenaStavki;
    }

    public void setCenaStavki(int cenaStavki) {
        this.cenaStavki = cenaStavki;
    }
   

    public void setBtnKreiraj(JButton btnKreiraj) {
        this.btnKreiraj = btnKreiraj;
    }

    public JButton getBtnPretrazi() {
        return btnPretrazi;
    }

    public void setBtnPretrazi(JButton btnPretrazi) {
        this.btnPretrazi = btnPretrazi;
    }

    public JButton getBtnSelect() {
        return btnSelect;
    }

    public void setBtnSelect(JButton btnSelect) {
        this.btnSelect = btnSelect;
    }

    public JButton getBtnIzaberiP() {
        return btnIzaberiP;
    }

    public void setBtnIzaberiP(JButton btnIzaberiP) {
        this.btnIzaberiP = btnIzaberiP;
    }

    public JButton getBtnIzaberiZ() {
        return btnIzaberiZ;
    }

    public void setBtnIzaberiZ(JButton btnIzaberiZ) {
        this.btnIzaberiZ = btnIzaberiZ;
    }

   

    public JButton getjButton1() {
        return btnIzaberiP;
    }

    public void setjButton1(JButton jButton1) {
        this.btnIzaberiP = jButton1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

 

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getLblPartner() {
        return lblPartner;
    }

    public void setLblPartner(JLabel jLabel5) {
        this.lblPartner = jLabel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

  

    public JTable getTblIznajmljivanje() {
        return tblIznajmljivanje;
    }

    public void setTblIznajmljivanje(JTable tblIznajmljivanje) {
        this.tblIznajmljivanje = tblIznajmljivanje;
    }

    public JTextField getTxtId() {
        return txtId;
    }

    public void setTxtId(JTextField txtId) {
        this.txtId = txtId;
    }



    public List<Iznajmljivanje> getIznajmljivanja() {
        return iznajmljivanja;
    }

    public void setIznajmljivanja(List<Iznajmljivanje> iznajmljivanja) {
        this.iznajmljivanja = iznajmljivanja;
    }

    public PoslovniPartner getPp() {
        return pp;
    }

    public void setPp(PoslovniPartner pp) {
        this.pp = pp;
    }

    public JButton getBtnStavke1() {
        return btnStavke1;
    }

    public void setBtnStavke1(JButton btnStavke1) {
        this.btnStavke1 = btnStavke1;
    }

    public JLabel getLblZaposleni() {
        return lblZaposleni;
    }

    public void setLblZaposleni(JLabel lblZaposleni) {
        this.lblZaposleni = lblZaposleni;
    }

    public Zaposleni getZaposleni() {
        return zaposleni;
    }

    public void setZaposleni(Zaposleni zaposleni) {
        this.zaposleni = zaposleni;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void setBtnIzmeni(JButton btnIzmeni) {
        this.btnIzmeni = btnIzmeni;
    }
     
    
    
    
   public void popuniTblIznajmljivanje() {
        ModelTblIznajmljivanje mtb= new ModelTblIznajmljivanje(iznajmljivanja);
        tblIznajmljivanje.setModel(mtb);
        
    }
    
    
    
     public void kreirajAddActionListener(ActionListener actionListener) {
        btnKreiraj.addActionListener(actionListener);
      
    }
     
    
    
       
       
       public void selektujAddActionListener(ActionListener actionListener) {
        btnSelect.addActionListener(actionListener);
      
    }
       
       public void izadjiAddActionListener(ActionListener actionListener) {
        btnIzadji.addActionListener(actionListener);
      
    }
       
       public void pretraziAddActionListener(ActionListener actionListener) {
        btnPretrazi.addActionListener(actionListener);
      
    }
       
       public void izaberiZAddActionListener(ActionListener actionListener) {
        btnIzaberiZ.addActionListener(actionListener);
      
    }
    
    public void izaberiPAddActionListener(ActionListener actionListener) {
        btnIzaberiP.addActionListener(actionListener);
      
    }
    
    public void promeniAddActionListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
      
    }
    
    
    
    public void stavkePAddActionListener(ActionListener actionListener) {
        btnStavke1.addActionListener(actionListener);
    }
    
}
