/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import forme.modeli_tabela.ModelTblStavkeIznajmljivanja;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import modeli.StavkeIznajmljivanja;
import modeli.Trotinet;
import operacije.Operacije;

/**
 *
 * @author User
 */
public class StavkeIznajmljivanjaForma extends javax.swing.JFrame {
    private Trotinet trotinet=null;
    private List<StavkeIznajmljivanja> stavke= new ArrayList<>();
    
    /**
     * Creates new form StavkeIznajmljivanjaForma
     */
    public StavkeIznajmljivanjaForma(int operacija) {
        initComponents();
        btnIzmeni.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnKreiraj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        btnIzaberi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblTrotinet = new javax.swing.JLabel();
        btnIzadji = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBrojSati = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtCena = new javax.swing.JTextField();
        btnIzmeni = new javax.swing.JButton();
        btnSelect = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblStavke);

        btnKreiraj.setText("Dodaj");

        btnObrisi.setText("Obrisi");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        btnIzaberi.setText("Izaberi trotinet");

        jLabel4.setText("Trotinet:");

        lblTrotinet.setText("Trotinet nije izabran");

        btnIzadji.setText("Izadji");

        jLabel2.setText("Broj sati:");

        jLabel1.setText("Cena po satu:");

        btnIzmeni.setText("Izmeni");

        btnSelect.setText("Izaberi stavku");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblTrotinet)
                                        .addGap(55, 55, 55)
                                        .addComponent(btnIzaberi))
                                    .addComponent(txtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(btnIzadji))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSelect)
                                    .addComponent(btnObrisi)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnKreiraj)
                        .addGap(55, 55, 55)
                        .addComponent(btnIzmeni)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzadji))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBrojSati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(btnIzaberi)
                            .addComponent(lblTrotinet))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKreiraj)
                            .addComponent(btnIzmeni))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSelect)
                                .addGap(37, 37, 37)
                                .addComponent(btnObrisi)
                                .addGap(140, 140, 140)))))
                .addGap(115, 115, 115))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObrisiActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIzaberi;
    private javax.swing.JButton btnIzadji;
    private javax.swing.JButton btnIzmeni;
    private javax.swing.JButton btnKreiraj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTrotinet;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojSati;
    private javax.swing.JTextField txtCena;
    // End of variables declaration//GEN-END:variables

    
    
    
    public Trotinet getTrotinet() {
        return trotinet;
    }
    
    public void setTrotinet(Trotinet trotinet) {
        this.trotinet = trotinet;
    }

    public JTextField getTxtBrojSati() {
        return txtBrojSati;
    }

    public void setTxtBrojSati(JTextField txtBrojSati) {
        this.txtBrojSati = txtBrojSati;
    }

    public JButton getBtnIzaberi() {
        return btnIzaberi;
    }

    public void setBtnIzaberi(JButton btnIzaberi) {
        this.btnIzaberi = btnIzaberi;
    }

    public JButton getBtnKreiraj() {
        return btnKreiraj;
    }

    public void setBtnKreiraj(JButton btnKreiraj) {
        this.btnKreiraj = btnKreiraj;
    }

    public JButton getBtnObrisi() {
        return btnObrisi;
    }

    public void setBtnObrisi(JButton btnObrisi) {
        this.btnObrisi = btnObrisi;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLblTrotinet() {
        return lblTrotinet;
    }

    public void setLblTrotinet(JLabel lblTrotinet) {
        this.lblTrotinet = lblTrotinet;
    }

    public JTable getTblStavke() {
        return tblStavke;
    }

    public void setTblStavke(JTable tblStavke) {
        this.tblStavke = tblStavke;
    }

    public JTextField getTxtCena() {
        return txtCena;
    }

    public void setTxtCena(JTextField txtCena) {
        this.txtCena = txtCena;
    }

    public JButton getBtnIzmeni() {
        return btnIzmeni;
    }

    public void setBtnIzmeni(JButton btnIzmeni) {
        this.btnIzmeni = btnIzmeni;
    }
    
    
    

    public void obrisiAddActionListener(ActionListener actionListener) {
        btnObrisi.addActionListener(actionListener);
      
    }
    
    public void kreirajAddActionListener(ActionListener actionListener) {
        btnKreiraj.addActionListener(actionListener);
      
    }
    
    public void izaberiAddActionListener(ActionListener actionListener) {
        btnIzaberi.addActionListener(actionListener);
      
    }
    
    public void izadjiAddActionListener(ActionListener actionListener) {
        btnIzadji.addActionListener(actionListener);
      
    }
    
    public void promeniAddActionListener(ActionListener actionListener) {
        btnIzmeni.addActionListener(actionListener);
      
    }
    
    public void popuniTblStavke() {
        ModelTblStavkeIznajmljivanja mtb= new ModelTblStavkeIznajmljivanja(stavke);
        tblStavke.setModel(mtb);
        
    }

    public List<StavkeIznajmljivanja> getStavke() {
        return stavke;
    }

    public void setStavke(List<StavkeIznajmljivanja> stavke) {
        this.stavke = stavke;
    }

    public JButton getBtnIzadji() {
        return btnIzadji;
    }

    public void setBtnIzadji(JButton btnIzadji) {
        this.btnIzadji = btnIzadji;
    }
    
    public void selektujAddActionListener(ActionListener actionListener) {
        btnSelect.addActionListener(actionListener);
      
    }
    
    
}
